// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm5N4cHPdP7MfO_z0xCFYh6V0ZNRjWbqU',
    appId: '1:1039765268462:web:8ddd335e86ff15caa210ff',
    messagingSenderId: '1039765268462',
    projectId: 'cattle-tracker-17c4c',
    authDomain: 'cattle-tracker-17c4c.firebaseapp.com',
    storageBucket: 'cattle-tracker-17c4c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCksMz6JgJhd0zOlmndC4btbyYZIe47-C8',
    appId: '1:1039765268462:android:553068d1c44bf0f6a210ff',
    messagingSenderId: '1039765268462',
    projectId: 'cattle-tracker-17c4c',
    storageBucket: 'cattle-tracker-17c4c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu8XW_41FeInwUX2mzHzSDGDrJdfFkQXM',
    appId: '1:1039765268462:ios:9873a1cc6fe4b9afa210ff',
    messagingSenderId: '1039765268462',
    projectId: 'cattle-tracker-17c4c',
    storageBucket: 'cattle-tracker-17c4c.firebasestorage.app',
    iosBundleId: 'com.example.cattleTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDu8XW_41FeInwUX2mzHzSDGDrJdfFkQXM',
    appId: '1:1039765268462:ios:9873a1cc6fe4b9afa210ff',
    messagingSenderId: '1039765268462',
    projectId: 'cattle-tracker-17c4c',
    storageBucket: 'cattle-tracker-17c4c.firebasestorage.app',
    iosBundleId: 'com.example.cattleTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCm5N4cHPdP7MfO_z0xCFYh6V0ZNRjWbqU',
    appId: '1:1039765268462:web:a8c5d3e9db8621f4a210ff',
    messagingSenderId: '1039765268462',
    projectId: 'cattle-tracker-17c4c',
    authDomain: 'cattle-tracker-17c4c.firebaseapp.com',
    storageBucket: 'cattle-tracker-17c4c.firebasestorage.app',
  );
}